"""ai-router: Embeddable LLM routing engine for Python."""

from .config.parse import parse_config
from .config.schema import (
    PROVIDER_IDS,
    BudgetRule,
    LimitRule,
    ModelRoute,
    PolicyWeights,
    ProviderId,
    RouterConfig,
    RoutingStrategy,
)
from .engine import (
    AttemptEvent,
    CallOptions,
    CallSummaryEvent,
    CandidateExplanation,
    RateLimitStore,
    RouterStats,
    RoutingEngine,
    RoutingExplanation,
    RoutingOptions,
    compute_cost,
)
from .errors import (
    AIRouterError,
    AllRoutesFailedError,
    AttemptRecord,
    ConfigError,
    DeadlineExceededError,
    ErrorKind,
    GuardrailBlockedError,
    ProviderError,
    RateLimitedError,
    UnsupportedProviderError,
    classify_status,
    is_key_related_kind,
    is_retryable_kind,
)
from .guardrails import (
    Guardrails,
    GuardrailVerdict,
    InputGuardrail,
    OutputGuardrail,
    run_guardrails,
)
from .limiter.memory import MemoryStore
from .limiter.redis import RedisRateLimitStore, RedisRouterStateStore
from .limiter.store import RateLimitDecision
from .providers.anthropic import AnthropicAdapter
from .providers.azure import AzureAdapter
from .providers.bedrock import BedrockAdapter
from .providers.gemini import GeminiAdapter
from .providers.openai import OpenAIAdapter
from .providers.presets import PROVIDER_PRESETS, ProviderPreset, get_preset
from .providers.registry import (
    get_adapter,
    is_supported,
    known_provider_ids,
    register_adapter,
)
from .providers.types import (
    AdapterContext,
    NormalizedRoute,
    ProviderAdapter,
    RawRequestOptions,
)
from .providers.vertex import VertexAdapter
from .router import AIRouter
from .routing.capabilities import (
    CapabilityRequirement,
    ModelCapabilities,
    RouteOp,
    capability_rejection,
    inferred_requirements,
)
from .routing.health import (
    DEFAULT_HALF_LIFE_MS,
    DEFAULT_SAMPLE_TTL_MS,
    KEY_COOLDOWN_CAP_MS,
    HealthTracker,
    KeyHealth,
    OpLatencyPercentiles,
    RouteHealthSnapshot,
    RouteOpStat,
    wilson_lower_bound,
)
from .routing.order import (
    ArrangeContext,
    ArrangeResult,
    PolicySignals,
    ScoreBreakdown,
    arrange_chain,
    balanced_scores,
    estimate_cost_usd,
    order_by_score,
    price_lookup,
    shrink_latencies,
)
from .routing.outcomes import OutcomeEvent, OutcomeStats, OutcomeTracker
from .routing.replay import (
    ReplayEvent,
    ReplayOptions,
    ReplayRequest,
    ReplayResult,
    replay_strategy,
)
from .routing.state import DEFAULT_STATE_KEY, RouterStateStore, infer_task
from .stream import collect_stream, stream_text, sync_collect_stream, sync_stream_text
from .types import (
    ChatChunk,
    ChatMessage,
    ChatRequest,
    ChatResponse,
    Choice,
    Delta,
    EmbeddingData,
    EmbeddingRequest,
    EmbeddingResponse,
    ProviderOptions,
    ResponseFormat,
    Role,
    TokenPrice,
    Tool,
    ToolCall,
    ToolCallDelta,
    Usage,
)

__all__ = [
    "DEFAULT_HALF_LIFE_MS",
    "DEFAULT_SAMPLE_TTL_MS",
    "DEFAULT_STATE_KEY",
    "KEY_COOLDOWN_CAP_MS",
    "PROVIDER_IDS",
    "PROVIDER_PRESETS",
    "AIRouter",
    "AIRouterError",
    "AdapterContext",
    "AllRoutesFailedError",
    "AnthropicAdapter",
    "ArrangeContext",
    "ArrangeResult",
    "AttemptEvent",
    "AttemptRecord",
    "AzureAdapter",
    "BedrockAdapter",
    "BudgetRule",
    "CallOptions",
    "CallSummaryEvent",
    "CandidateExplanation",
    "CapabilityRequirement",
    "ChatChunk",
    "ChatMessage",
    "ChatRequest",
    "ChatResponse",
    "Choice",
    "ConfigError",
    "DeadlineExceededError",
    "Delta",
    "EmbeddingData",
    "EmbeddingRequest",
    "EmbeddingResponse",
    "ErrorKind",
    "GeminiAdapter",
    "GuardrailBlockedError",
    "GuardrailVerdict",
    "Guardrails",
    "HealthTracker",
    "InputGuardrail",
    "KeyHealth",
    "LimitRule",
    "MemoryStore",
    "ModelCapabilities",
    "ModelRoute",
    "NormalizedRoute",
    "OpLatencyPercentiles",
    "OpenAIAdapter",
    "OutcomeEvent",
    "OutcomeStats",
    "OutcomeTracker",
    "OutputGuardrail",
    "PolicySignals",
    "PolicyWeights",
    "ProviderAdapter",
    "ProviderError",
    "ProviderId",
    "ProviderOptions",
    "ProviderPreset",
    "RateLimitDecision",
    "RateLimitStore",
    "RateLimitedError",
    "RawRequestOptions",
    "RedisRateLimitStore",
    "RedisRouterStateStore",
    "ReplayEvent",
    "ReplayOptions",
    "ReplayRequest",
    "ReplayResult",
    "ResponseFormat",
    "Role",
    "RouteHealthSnapshot",
    "RouteOp",
    "RouteOpStat",
    "RouterConfig",
    "RouterStateStore",
    "RouterStats",
    "RoutingEngine",
    "RoutingExplanation",
    "RoutingOptions",
    "RoutingStrategy",
    "ScoreBreakdown",
    "TokenPrice",
    "Tool",
    "ToolCall",
    "ToolCallDelta",
    "UnsupportedProviderError",
    "Usage",
    "VertexAdapter",
    "arrange_chain",
    "balanced_scores",
    "capability_rejection",
    "classify_status",
    "collect_stream",
    "compute_cost",
    "estimate_cost_usd",
    "get_adapter",
    "get_preset",
    "infer_task",
    "inferred_requirements",
    "is_key_related_kind",
    "is_retryable_kind",
    "is_supported",
    "known_provider_ids",
    "order_by_score",
    "parse_config",
    "price_lookup",
    "register_adapter",
    "replay_strategy",
    "run_guardrails",
    "shrink_latencies",
    "stream_text",
    "sync_collect_stream",
    "sync_stream_text",
    "wilson_lower_bound",
]
